joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 4
    scale_linear:
      x: 0.2
    scale_linear_turbo:
      x: 0.5

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 0.2  
    scale_angular_turbo:
      yaw: 0.5


    enable_button: 7 # Start button in the RedGear/Xbox controller
    enable_turbo_button: 5 # RB in the RedGear/Xbox controller

    require_enable_button: true